name: Build docs

on:
  pull_request:
    paths:
      - docs/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
    - name: Install Python packages
      run: pip install Sphinx
    - name: Build docs
      run: make -C docs/ html
